[package]
name = "rosty_xmlrpc"
version = "0.1.0"
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
hyper="0.13"
futures = "0.3"
xmlrpc_fmt = { path="../rosty_xmlrpc_fmt", package ="rosty_xmlrpc_fmt" }
